DMR Routing Implementation
buerokratt/DMR.NET pull request #34
Opened 2022-05-26 12:49 UTC by guypritchard

2022-05-30 11:07 UTC, yahya130 commented on src/Dmr.Api/Controllers/DMRController.cs
> +    public class DmrController : ControllerBase
Minor point, would it make sense calling this class MessagesController? as the route suggests, and it looks like the logic encapsulates message relate data

2022-05-30 11:27 UTC, yahya130 commented on src/Dmr.Api/Controllers/DMRController.cs
> +        /// <returns>204 Accepted or 400 BadRequest</returns>
Looks like specific return types, this might be appropriate:
```suggestion
        /// <returns>204 Accepted or 400 BadRequest</returns>
        [ProducesResponseType(StatusCodes.Status204NoContent)]
        [ProducesResponseType(StatusCodes.Status400BadRequest)]
```

2022-05-30 11:29 UTC, yahya130 commented on src/Dmr.Api/Controllers/DMRController.cs
> +            if (headers == null)
could we add this in as well since the HeadersInput class in HeadersInput.cs seems to contain validation logic? 
```suggestion
            if (headers == null || !modelState.IsValid)
```

2022-05-30 11:44 UTC, guypritchard commented on src/Dmr.Api/Controllers/DMRController.cs
> +    public class DmrController : ControllerBase
Can do!

2022-05-30 11:54 UTC, guypritchard commented on src/Dmr.Api/Controllers/DMRController.cs
> +            if (headers == null)
Model validation occurs before this method is called so we shouldn't need to do this explicitly.  That null check was just belt and braces honestly - we shouldn't even be in here if there aren't any headers specified. I'll take that null check out - it shouldn't happen.

2022-05-30 16:45 UTC, yahya130 approved these changes

2022-05-30 22:02 UTC, decodingahmed requested changes
I've added a few comment, but this is looking great. Nice work @priyankasharma55 and @guypritchard.

2022-05-30 22:02 UTC, decodingahmed commented on src/Dmr.Api/Services/AsyncProcessor/AsyncProcessorService.cs
> +        protected AsyncProcessorService(IHttpClientFactory httpClientFactory, TSettings config, ILogger logger)
I'm wondering whether you can simplify the template for this and drop `TSettings`. You aren't using it in the abstract layers anyway.  Maybe I'm missing something though, so please correct me.

2022-05-30 22:02 UTC, decodingahmed commented on src/Dmr.Api/Services/AsyncProcessor/AsyncProcessorService.cs
> +                await ProcessRequestAsync(request).ConfigureAwait(true);
```suggestion
                await ProcessRequestAsync(request).ConfigureAwait(false);
```

2022-05-30 22:02 UTC, decodingahmed commented on src/Dmr.Api/Services/MessageForwarder/Extensions/ServiceCollectionExtensions.cs
> +        /// Helper extension configure IOC container with <see cref="MessageForwarderService"/> Service and associated services.
```suggestion
        /// Helper extension to configure IOC container with <see cref="MessageForwarderService"/> Service and associated services.
```

2022-05-30 22:02 UTC, decodingahmed commented on src/Dmr.Api/Services/MessageForwarder/MessageForwarderException.cs
> +          System.Runtime.Serialization.StreamingContext context) : base(info, context) { }
Could you add the `System.Runtime.Serialization` namespace above and remove it from these lines please?

2022-05-30 22:02 UTC, decodingahmed commented on src/Dmr.Api/Services/MessageForwarder/MessageForwarderService.cs
> +                    await SendMessageForClassification(payload.Payload, payload.Headers).ConfigureAwait(true);
```suggestion
                    await SendMessageForClassification(payload.Payload, payload.Headers).ConfigureAwait(false);
```

2022-05-30 22:02 UTC, decodingahmed commented on src/Dmr.Api/Services/MessageForwarder/MessageForwarderService.cs
> +                await ResolveRecipientAndForward(payload.Payload, payload.Headers).ConfigureAwait(true);
```suggestion
                await ResolveRecipientAndForward(payload.Payload, payload.Headers).ConfigureAwait(false);
```

2022-05-30 22:02 UTC, decodingahmed commented on src/Dmr.Api/Services/MessageForwarder/MessageForwarderService.cs
> +                await NotifySenderOfError(payload.Headers).ConfigureAwait(true);
```suggestion
                await NotifySenderOfError(payload.Headers).ConfigureAwait(false);
```

2022-05-30 22:02 UTC, decodingahmed commented on src/Dmr.Api/Services/MessageForwarder/MessageForwarderService.cs
> +            }
You've already validated these params in other calling methods so this is redundant. If you do want to keep this guard then please also validate `payload`

2022-05-30 22:02 UTC, decodingahmed commented on src/Dmr.Api/Services/MessageForwarder/MessageForwarderService.cs
> +                participantEndpoint = await centOps.TryGetEndpoint(headers.XSendTo).ConfigureAwait(true);
```suggestion
                participantEndpoint = await centOps.TryGetEndpoint(headers.XSendTo).ConfigureAwait(false);
```

Please also set this to `false` for the rest of the instances in this file

2022-05-30 22:02 UTC, decodingahmed commented on src/Dmr.Api/Services/MessageForwarder/MessageForwarderService.cs
> +                    throw new KeyNotFoundException($"Participant not found with id '{headers.XSendTo}'");
nit: Sorry, the current message is a little difficult to read. Feel free to ignore if you think it is correct though. I'm foggy today.
```suggestion
                    throw new KeyNotFoundException($"Participant with id '{headers.XSendTo}' not found");
```

2022-05-30 22:02 UTC, decodingahmed commented on src/Dmr.Api/Services/CentOps/ICentOps.cs
> +        Task<Uri?> TryGetEndpoint(string chatbotId);
I guess I'm being super pedantic here but the `TryGet` pattern usually returns a `bool` with an `out var` variable.  Maybe `GetEndpoint` or `FetchEndpoint` might work better.  Feel free to ignore this suggestion though.

2022-05-30 22:02 UTC, decodingahmed commented on src/Dmr.Api/Services/CentOps/ICentOps.cs
> +    public interface ICentOps
nit: Technically, `ICentopsService` but I appreciate that this will be refactored when real CentOps is integrated

2022-05-30 22:02 UTC, decodingahmed commented on src/Dmr.Api/Services/MessageForwarder/MessageForwarderService.cs
> +                    throw new KeyNotFoundException($"Participant not found with id '{headers.XSentBy}'");
```suggestion
                    throw new KeyNotFoundException($"Participant with id '{headers.XSentBy}' not found");
```

2022-05-30 22:02 UTC, decodingahmed commented on src/Dmr.Api/Services/MessageForwarder/MessageForwarderService.cs
> +            content.Headers.Add(Constants.ContentTypeHeaderName, headers.ContentType ?? "text/plain");
Instead of removing and adding, is this going to work?

```suggestion
            _ = content.Headers.ContentType = new MediaTypeHeaderValue(headers.ContentType ?? "text/plain");
```

2022-05-30 22:02 UTC, decodingahmed commented on src/Dmr.UnitTests/DMRControllerTests.cs
> +            var result = await sut.PostAsync(new HeadersInput { XSendTo = "Classifier" }).ConfigureAwait(true);
```suggestion
            var result = await sut.PostAsync(new HeadersInput { XSendTo = "Classifier" }).ConfigureAwait(false);
```

Please also update all the ConfigureAwaits in this file to pass in `false`

2022-05-31 07:59 UTC, guypritchard commented on src/Dmr.Api/Services/AsyncProcessor/AsyncProcessorService.cs
> +        protected AsyncProcessorService(IHttpClientFactory httpClientFactory, TSettings config, ILogger logger)
This borrows heavily from the cleverness of the original code - but we do use the ClientName to name the HttpClient instance we create in the constructor.

2022-05-31 08:00 UTC, guypritchard commented on src/Dmr.Api/Services/MessageForwarder/MessageForwarderException.cs
> +          System.Runtime.Serialization.StreamingContext context) : base(info, context) { }
This was automagically created - but yep will do.

2022-05-31 08:03 UTC, guypritchard commented on src/Dmr.Api/Services/CentOps/ICentOps.cs
> +    public interface ICentOps
Yep - renamed.

2022-05-31 08:04 UTC, guypritchard commented on src/Dmr.Api/Services/MessageForwarder/MessageForwarderService.cs
> +            content.Headers.Add(Constants.ContentTypeHeaderName, headers.ContentType ?? "text/plain");
Let me give that a try - looks nicer.

2022-05-31 08:10 UTC, guypritchard commented on src/Dmr.UnitTests/DMRControllerTests.cs
> +            var result = await sut.PostAsync(new HeadersInput { XSendTo = "Classifier" }).ConfigureAwait(true);
Done

2022-05-31 08:12 UTC, guypritchard commented on src/Dmr.Api/Services/CentOps/ICentOps.cs
> +        Task<Uri?> TryGetEndpoint(string chatbotId);
Okay - I'll use FetchEndpoint - the code analysis was warning me out params on an interface wasn't cool.

2022-05-31 08:14 UTC, martinkearn approved these changes

2022-05-31 08:14 UTC, martinkearn commented on src/Dmr.Api/Models/Constants.cs
> +        public const string XSentByHeaderName = "X-Sent-By";
As noted, in the other PR, there is an opportunity to standardise on these. It is not for this PR though and tracked under https://github.com/buerokratt/Cross-functional-requirements/issues/46. Please resolve this right away, I've just put it here for future reference.

2022-05-31 08:16 UTC, guypritchard commented on src/Dmr.Api/Services/MessageForwarder/MessageForwarderService.cs
> +            content.Headers.Add(Constants.ContentTypeHeaderName, headers.ContentType ?? "text/plain");
Yep - nice.

2022-05-31 09:00 UTC, guypritchard commented on src/Dmr.Api/Services/MessageForwarder/MessageForwarderService.cs
> +                    throw new KeyNotFoundException($"Participant not found with id '{headers.XSendTo}'");
They both read okay to me - but I'll take yours.

2022-05-31 09:01 UTC, decodingahmed approved these changes
Ship it! :)

2022-05-31 09:03 UTC, guypritchard commented on src/Dmr.Api/Services/MessageForwarder/MessageForwarderService.cs
> +            }
I was fighting with code analysis here.  Red lines appear all over the place indicating I should be checking these values.  I stopped fighting and checked the parameters it was telling me about.  Agreed - these values are already checked, but it seems the analysis happens on a function-by-function basis.

2022-05-31 09:05 UTC, decodingahmed commented on src/Dmr.Api/Services/MessageForwarder/MessageForwarderService.cs
> +            }
Fair enough, yeah let's not fight code analysis now 😅

2022-05-31 11:37 UTC, merged