Adding in a few fixes
buerokratt/DMR.NET pull request #41
Opened 2022-06-07 14:26 UTC by guypritchard

2022-06-07 22:08 UTC, decodingahmed requested changes
Just requesting some minor changes in the PR. The rest looks good to me 😊

2022-06-07 22:08 UTC, decodingahmed commented on src/Dmr.Api/Services/AsyncProcessor/AsyncProcessorHostedService.cs
> +            logger.AsyncProcessorStateChange("AsyncProcessor Started");
Just wanted to clarify that the `StartAsync` and `StopAsync` methods (usually) only get called once during the lifetime of the application. It doesn't make sense for these to be logged at "state changed".

2022-06-07 22:08 UTC, decodingahmed commented on src/Dmr.Api/Services/AsyncProcessor/AsyncProcessorHostedService.cs
> -                self.logger.AsyncProcessorStateChange("started");
I think these logs should be remain where they are as they capture the start and end of the processing period. Unless you're happy with the logging that happens in the service? Lemme know and I'll close this comment :)

2022-06-07 22:08 UTC, decodingahmed commented on src/Dmr.Api/Services/MessageForwarder/MessageForwarderService.cs
> +                    await NotifySenderOfError(payload.Headers).ConfigureAwait(true);
```suggestion
                    await NotifySenderOfError(payload.Headers).ConfigureAwait(false);
```

2022-06-07 22:17 UTC, guypritchard commented on src/Dmr.Api/Services/AsyncProcessor/AsyncProcessorHostedService.cs
> -                self.logger.AsyncProcessorStateChange("started");
Anecdotally, when I was working with these logs they didn't seem to be adding much - they seemed to clutter the logging output with started/completed messages.  Maybe these logs want to be something else?  I don't know...  If you want to keep them we certainly can.

2022-06-07 22:18 UTC, guypritchard commented on src/Dmr.Api/Services/AsyncProcessor/AsyncProcessorHostedService.cs
> +            logger.AsyncProcessorStateChange("AsyncProcessor Started");
Yep - that's what I was seeing.  Just to clarify, Is it the naming you're not keen on or the logging at all?

2022-06-07 22:22 UTC, decodingahmed commented on src/Dmr.Api/Services/AsyncProcessor/AsyncProcessorHostedService.cs
> -                self.logger.AsyncProcessorStateChange("started");
I'm with you that maybe they are trying to do something else.  My original intention (when I wrote one of the first iterations) for these logs was to track how long it takes for us to process requests. But I suppose we could wrap a stopwatch around this call and do a single log instead.

Side note: would be cool to get the number of processed requests from the `ProcessRequestsAsync` method and log that too. Would give us a clear view of what is going on.

FTR, I think the above thoughts are just thoughts, not suggesting that you do them in this PR

2022-06-08 14:56 UTC, guypritchard commented on src/Dmr.Api/Services/AsyncProcessor/AsyncProcessorHostedService.cs
> -                self.logger.AsyncProcessorStateChange("started");
Okay - I've added something which will count the number of messages processed and the time taken.  See what you think...

2022-06-08 15:10 UTC, decodingahmed commented on src/Dmr.Api/Services/AsyncProcessor/AsyncProcessorHostedService.cs
> -                self.logger.AsyncProcessorStateChange("started");
Lovely - thank you dude!

2022-06-08 15:10 UTC, decodingahmed approved these changes
Le ship-it!

2022-06-09 05:00 UTC, tonistuulNG approved these changes

2022-06-09 08:41 UTC, decodingahmed approved these changes

2022-06-09 10:15 UTC, merged